/**
 * Created by cc on 2016/1/15.
 */
define(['app/roc/weakness/weaknessDo',
        'app/roc/weakness/getStuListDo',
        'app/roc/ptCourseList/rocPtCourseListDo',
        'app/roc/ptCourseList/rocPushByKnowledgeDo',
        'app/roc/ptCourseList/rocPushByQuestionDo',
        'app/roc/ptCourseList/rocPushByAllDo',
        'app/roc/countManage/countManageDo',
        'app/roc/countManage/listenCardDetailDo',
        'app/roc/countManage/ptCountDetailDo',
        'app/roc/countManage/ptSeatDetailDo',
        'app/roc/countManage/useCostCountDetailDo',
        'app/roc/countManage/schRevenueCountDo',
        'app/roc/countManage/schRevenueCountDetailDo'],function(){
    /*
        主要用来加载各个控制器（所有的控制器都将在这个文件中被加载）,
        除此之外再不用做其他，因为我们可以有很多个控制器文件，
        按照具体需要进行添加。
     */
});
